import { useEffect, useMemo, useState } from 'react'
import './cognitive-timeline-v2.css'

type EventItem={id:string;event_type:string;phase:string;source:string;cycle_id?:string;payload:any;importance:number;timestamp:number;correlation_id?:string;parent_event_id?:string;visibility:string}

export default function CognitiveTimelineV2(){
 const [events,setEvents]=useState<EventItem[]>([]); const [stats,setStats]=useState<any>({total:0,cycles:0,phases:[],event_types:[]}); const [phase,setPhase]=useState(''); const [source,setSource]=useState(''); const [type,setType]=useState(''); const [cycle,setCycle]=useState(''); const [selected,setSelected]=useState<EventItem|null>(null); const [live,setLive]=useState(false)
 const load=async()=>{const p=new URLSearchParams(); if(phase)p.set('phase',phase); if(source)p.set('source',source); if(type)p.set('event_type',type); if(cycle)p.set('cycle_id',cycle); const [a,b]=await Promise.all([fetch('/api/events/v2/timeline?'+p).then(r=>r.json()),fetch('/api/events/v2/stats').then(r=>r.json())]); setEvents(a.items||[]); setStats(b||{})}
 useEffect(()=>{load(); const id=setInterval(load,3000); return()=>clearInterval(id)},[phase,source,type,cycle])
 useEffect(()=>{let ws:WebSocket|undefined; try{const proto=location.protocol==='https:'?'wss':'ws'; ws=new WebSocket(`${proto}://${location.host}/ws/events`); ws.onopen=()=>setLive(true); ws.onclose=()=>setLive(false)}catch{} return()=>ws?.close()},[])
 const phaseOptions=useMemo(()=>Array.from(new Set((stats.phases||[]).map((x:any)=>x.phase))),[stats]); const typeOptions=useMemo(()=>Array.from(new Set((stats.event_types||[]).map((x:any)=>x.event_type))),[stats])
 return <section className="ct-shell"><header className="ct-header"><div><span>COGNITIVE EVENT BUS V2</span><h2>Unified Cognitive Timeline</h2><p>Persistent computational event history across the cognitive loop.</p></div><div className={live?'ct-live on':'ct-live'}><i/> {live?'LIVE':'OFFLINE'}</div></header>
 <div className="ct-stats"><div><b>{stats.total||0}</b><span>events</span></div><div><b>{stats.cycles||0}</b><span>cycles</span></div><div><b>{stats.phases?.length||0}</b><span>phases</span></div><div><b>{stats.event_types?.length||0}</b><span>event types</span></div></div>
 <div className="ct-filters"><select value={phase} onChange={e=>setPhase(e.target.value)}><option value="">All phases</option>{phaseOptions.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="">All event types</option>{typeOptions.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Source" value={source} onChange={e=>setSource(e.target.value)}/><input placeholder="Cycle ID" value={cycle} onChange={e=>setCycle(e.target.value)}/><button onClick={load}>Refresh</button></div>
 <div className="ct-body"><div className="ct-list">{events.length===0?<div className="ct-empty">No events match the current filters.</div>:events.map(e=><button className="ct-event" key={e.id} onClick={()=>setSelected(e)}><div className="ct-dot"/><div className="ct-event-main"><div><strong>{e.event_type}</strong><span>{e.phase}</span></div><p>{e.source} · {new Date(e.timestamp*1000).toLocaleTimeString()}</p><small>{e.cycle_id||'no cycle'} · importance {(e.importance??0).toFixed(2)}</small></div></button>)}</div>
 {selected&&<aside className="ct-detail"><button className="ct-close" onClick={()=>setSelected(null)}>×</button><span>EVENT DETAIL</span><h3>{selected.event_type}</h3><dl><dt>Phase</dt><dd>{selected.phase}</dd><dt>Source</dt><dd>{selected.source}</dd><dt>Cycle</dt><dd>{selected.cycle_id||'—'}</dd><dt>Correlation</dt><dd>{selected.correlation_id||'—'}</dd><dt>Parent</dt><dd>{selected.parent_event_id||'—'}</dd></dl><pre>{JSON.stringify(selected.payload,null,2)}</pre></aside>}
 </div><div className="ct-note">Scientific boundary: this timeline records software events, coordination, and state transitions. It does not establish subjective consciousness, sentience, or experience.</div></section>
}
