import React,{useEffect,useRef,useState}from'react';
import{Activity,CheckCircle2,Circle,RefreshCw,ShieldAlert,BrainCircuit,Zap}from'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
const phases=['perception','attention','workspace','memory','self_model','world_model','internal_state','goals','reasoning','planning','safety','execution','observation','reflection','learning','consolidation','idle'];
const label=(x:string)=>x.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function CognitiveLoop(){
 const[data,setData]=useState<any>({});const[input,setInput]=useState('');const[running,setRunning]=useState(false);const[events,setEvents]=useState<any[]>([]);const[error,setError]=useState('');const ws=useRef<WebSocket|null>(null);
 const load=()=>fetch(API+'/api/loop').then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>{});
 useEffect(()=>{load();const t=setInterval(load,2000);let url=API.replace(/^http/,'ws')+'/ws/events';try{const socket=new WebSocket(url);ws.current=socket;socket.onmessage=e=>{try{const v=JSON.parse(e.data);setEvents(x=>[v,...x].slice(0,80));load()}catch{}}}catch{}return()=>{clearInterval(t);ws.current?.close()}},[]);
 const run=async()=>{if(!input.trim()||running)return;setRunning(true);setError('');try{const r=await fetch(API+'/api/loop/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:input.trim()})});if(!r.ok)throw Error(await r.text());setData(await r.json());setInput('')}catch(e){setError(String(e).replace(/^Error:/,''))}finally{setRunning(false);load()}};
 const cycle=data?.cycle||data||{};const current=cycle.phase||cycle.current_phase||'idle';const done=new Set(cycle.completed_phases||cycle.completed||[]);const status=cycle.status||'idle';
 return <div className="loopPage">
  <section className="loopHero panel"><div><div className="eyebrow">COGNITIVE LOOP V2</div><h2>Live Cognitive Cycle</h2><p>Observable orchestration from perception through reflection and consolidation. This is a cognitive architecture, not a claim of subjective consciousness.</p></div><div className="loopStatus"><span className={'statusBadge '+status}>{status}</span><small>Cycle {cycle.id??'—'}</small></div></section>
  <section className="loopRun panel"><div className="loopInput"><BrainCircuit size={17}/><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Start a cognitive cycle with an objective..."/><button className="primaryBtn" onClick={run} disabled={running}>{running?<RefreshCw className="spin" size={14}/>:<Zap size={14}/>} {running?'Running':'Run cycle'}</button></div>{error&&<small className="loopError">{error}</small>}</section>
  <section className="loopGrid"><div className="panel"><div className="panelTitle"><h2>Phase Timeline</h2><span>{label(current)}</span></div><div className="phaseTimeline">{phases.map((p,i)=>{const active=p===current;const complete=done.has(p);return <div className={'phase '+(active?'active ':'')+(complete?'complete':'')} key={p}><div className="phaseMarker">{complete?<CheckCircle2 size={15}/>:active?<Activity size={15}/>:<Circle size={13}/>}</div><div><strong>{label(p)}</strong><small>{complete?'completed':active?'active':'waiting'}</small></div>{i<phases.length-1&&<i className="phaseLine"/>}</div>})}</div></div>
   <div className="stack"><section className="panel"><div className="panelTitle"><h2>Cycle State</h2><span>LIVE</span></div><div className="stateRows"><div><span>Current phase</span><b>{label(current)}</b></div><div><span>Status</span><b>{status}</b></div><div><span>Uncertainty</span><b>{Math.round((cycle.uncertainty??0)*100)}%</b></div><div><span>Confidence</span><b>{Math.round((cycle.confidence??0)*100)}%</b></div><div><span>Energy</span><b>{Math.round((cycle.energy??0)*100)}%</b></div></div></section><section className="panel safetyPanel"><ShieldAlert size={17}/><div><b>Safety boundary</b><small>External actions remain approval-gated. The loop does not execute arbitrary system, browser, credential, or network actions.</small></div></section></div></section>
  <section className="loopGrid lowerLoop"><section className="panel"><div className="panelTitle"><h2>Phase Outputs</h2><span>INSPECTABLE</span></div><pre className="loopPre">{JSON.stringify(cycle.outputs||cycle.phase_outputs||{},null,2)}</pre></section><section className="panel"><div className="panelTitle"><h2>Event Stream</h2><span>{events.length}</span></div><div className="eventList">{events.map((e,i)=><div className="eventRow" key={i}><small>{e.phase||e.type||'event'}</small><span>{typeof e.message==='string'?e.message:JSON.stringify(e)}</span></div>)}{!events.length&&<div className="emptyBox">Waiting for cognitive-loop events.</div>}</div></section></section>
 </div>
}
